config/routes.rb
Rails.application.routes.draw do
  root to: "root#index"
  devise_for :users, controllers: { registrations: "registrations" }
  resources :groups, only: [:new, :create, :index, :show]
  resources :budgets, only: [:new, :create]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/budget.rb
class Budget < ApplicationRecord
  belongs_to :author, class_name: 'User'

  validates :name, presence: true
  validates :amount, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :author, class_name: 'User'

  validates :name, presence: true
  validates :icon, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :budgets, dependent: :destroy
  has_many :groups, dependent: :destroy

  validates :name, presence: true
  validates :email, presence: true
  validates :password, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(_resource)
    groups_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name])
  end
end

app/controllers/budgets_controller.rb
class BudgetsController < ApplicationController
  def new
    @budget = Budget.new
    @categories = Group.where(author_id: current_user.id)
  end

  def create
    new_budget = Budget.new(name: params[:budget][:name], amount: params[:budget][:amount], group_id: params[:budget][:group_id], author: current_user)
    if new_budget.save
      redirect_to group_path(params[:budget][:group_id])
    else
      render :new
    end
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def new
    @group = Group.new
  end

  def create
    new_category = Group.new(name: params[:group][:name], icon: params[:group][:icon], author: current_user)
    if new_category.save
      redirect_to groups_path
    else
      render :new
    end
  end

  def index
    @groups = Group.where(author_id: current_user.id)
    @budgets = Budget.all
  end

  def show
    @budgets = Budget.where(group_id: params[:id]).order('created_at DESC')
    @total_price = 0
    @budgets.each do |budget|
      @total_price += budget.amount
    end
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected

  def after_sign_up_path_for(_resource)
    groups_path
  end
end

app/controllers/root_controller.rb
class RootController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/budgets_helper.rb
module BudgetsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/root_helper.rb
module RootHelper
end

app/views/budgets/new.html.erb
<div class="bg-main flex justify-center p-4">
<%= link_to groups_path, class: "justify-self-start text-white text-2xl font-black" do %>
  <i class="fa-solid fa-arrow-left"></i>
<% end %>
<h2 class="text-white text-2xl my-0 mx-auto">Create Transaction</h2>
<input type="submit" value="Save" form="new_transaction" class="text-white">
</div>

<%= form_with model: @budget,  id: 'new_transaction', class: 'flex flex-col items-center mt-2', url: budgets_path do |form| %>
  <div class="w-3/5 mb-2">
    <%= form.text_field :name, placeholder: 'Name', class: 'w-full' %>
  </div>
  <div class="w-3/5 mb-2">
    <%= form.number_field :amount, in: 1.0..99999999.0, placeholder: 'Amount', class: 'w-full' %>
  </div>
  <div class="w-3/5 mb-2 text-text">
    <%= form.label :category %><br>
    <%= form.select :group_id, (@categories.map{|category| [category.name, category.id]}),{},{:class => 'w-full'} %>
  </div>
<% end %>

app/views/groups/index.html.erb
<div class="bg-main text-white text-center p-4 flex justify-center items-center">
  <i class="fa-solid fa-bars text-xl"></i>
  <h2 class="text-2xl font-bold my-0 mx-auto">All Categories</h2>
  <%= button_to destroy_user_session_path, method: :delete, form: {  data: { turbo: :false } }, class:"text-white p-2 font-600" do %>
    <i class="fa-solid fa-right-from-bracket text-xl"></i>
  <%end%>
</div>
<% @groups.each do |group| %>
  <% total_price = 0 %>
  <% @budgets.each do |budget| %>
      <% total_price += budget.amount if budget.group_id == group.id %>
  <% end %>
  <div class="grid grid-cols-3 my-4 mx-auto w-3/4 p-4 bg-zinc-100">
    <%= image_tag "#{group.icon}", class: "w-14 h-14 my-0 mx-auto" %>
    <div class="my-auto mx-auto">
    <h2 class="text-xl text-main"> <%= link_to group.name, group_path(group.id) %> </h2>
    <p class="text-xs mt-4"><%= group.created_at.strftime("%d %b %Y") %></p>
    </div>
    <p class="my-auto mx-auto">$<%= total_price %></p>
  </div>
<% end %>

<div class="text-center bg-secondary p-5">
  <%= link_to 'Add a new category', new_group_path, class: "bg-secondary text-white text-lg p-3 border-2 border-white md:text-xl " %>
</div>

app/views/groups/new.html.erb
<div class="bg-main flex justify-center p-4">
<%= link_to groups_path, class: "justify-self-start text-white text-2xl font-black" do %>
  <i class="fa-solid fa-arrow-left"></i>
<% end %>
<h2 class="text-white text-2xl my-0 mx-auto">Create Category</h2>
<input type="submit" value="Save" form="new_group" class="text-white">
</div>

<%= form_with model: @group, id: 'new_group', class: 'flex flex-col items-center mt-2', url: groups_path do |form| %>
  <div class="w-3/5 mb-2">
    <%= form.text_field :name, placeholder: 'Category Name', class: 'w-full' %>
  </div>
  <div class="w-3/5 mb-2">
    <%= form.text_field :icon, placeholder: 'Icon url', class: 'w-full' %>
  </div>
<% end %>

app/views/groups/show.html.erb
<div class="bg-main flex justify-center p-4">
<%= link_to groups_path, class: "justify-self-start text-white text-2xl font-black" do %>
  <i class="fa-solid fa-arrow-left"></i>
<% end %>
<h2 class="text-white text-2xl my-0 mx-auto">TRANSACTIONS</h2>
</div>
<div class="flex justify-between m-4">
<p class="text-xl">Total Price: </p>
<p><b>$<%= @total_price.round(2) %></b></p>
</div>

<% @budgets.each do |budget| %>
  <div class="flex justify-between items-center p-4 bg-zinc-100 mb-4">
    <h3 class="mr-4 text-lg"><%= budget.name %></h3>
    <p>$<%= budget.amount %></p>
  </div>
<% end %>

<div class="text-center bg-secondary p-5">
  <%= link_to 'Add a new transaction', new_budget_path, class: "bg-secondary text-white p-3 border-2 border-white text-lg md:text-xl" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/root/index.html.erb
<div class='h-screen flex items-center justify-center'>
  <div class="flex flex-col space-y-60 w-2/4 text-center text-text">
    <h1 class="text-4xl font-proxima_bold">Budget App</h1>
    <div class="flex flex-col">
      <%= link_to 'LOG IN', new_user_session_path, class: "border-2 border-transparent p-4 hover:bg-main hover:text-white" %>
      <%= link_to 'SIGN UP', new_user_registration_path, class: "border-2 border-transparent p-4 hover:bg-main hover:text-white" %>
    </div>
  </div>
</div>